Revolver/Revolver/Models/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Revolver.Models
{
    public class Image
    {
        public int Id { get; set; }
        [Required]
        public string Url { get; set; }
        [Required]
        [StringLength(maximumLength: 1000, MinimumLength = 1)]
        public string Name { get; set; }
        public string Description { get; set; }
        public int? ItemId { get; set; }
        [ForeignKey("ItemId")]
        public Item Item { get; set; }
        public int? StoryId { get; set; }
        [ForeignKey("StoryId")]
        public Story Story { get; set; }
        public int? DesignerId { get; set; }
        [ForeignKey("DesignerId")]
        public Designer Designer { get; set; }
        public bool IsThumb { get; set; }


    }
}

Revolver/Revolver/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Revolver.Models;

namespace Revolver.Controllers
{
    [Authorize]
    public class ImagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private readonly string[] allowedExtensions = { ".jpeg", ".jpg", ".png", ".gif" };

        // GET: Images
        public ActionResult Index()
        {
            var images = db.Images.Include(i => i.Item).Include(i => i.Story);
            return View(images.ToList());
        }

        // GET: Images/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image image = db.Images.Include(i => i.Item).Include(i => i.Story).Include(i=>i.Item.Designer).FirstOrDefault(i => i.Id == id);
            if (image == null)
            {
                return HttpNotFound();
            }
            return View(image);
        }

        // GET: Images/Create
        public ActionResult Create()
        {
            ViewBag.ItemId = new SelectList(db.Items, "Id", "Name");
            ViewBag.StoryId = new SelectList(db.Stories, "Id", "Title");
            ViewBag.DesignerId = new SelectList(db.Designers, "Id", "LastName");

            return View();
        }

        // POST: Images/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Url,Name,Description,ItemId,StoryId,DesignerId,IsThumb")] Image image)
        {
            ViewBag.ItemId = new SelectList(db.Items, "Id", "Name", image.ItemId);
            ViewBag.StoryId = new SelectList(db.Stories, "Id", "Title", image.StoryId);
            ViewBag.DesignerId = new SelectList(db.Designers, "Id", "LastName", image.DesignerId);

            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files[0];
                    if (file.ContentLength > 0)
                    {
                        var extension = Path.GetExtension(file.FileName);
                        if (!allowedExtensions.Contains(extension.ToLower()))
                        {
                            ModelState.AddModelError(string.Empty, "File extension not allowed!");
                            return View(image);
                        }
                        var fileName = image.Name;
                        image.Url = Path.Combine("~/Resources", fileName + extension);
                        var fullPath = Server.MapPath(image.Url);
                        if (System.IO.File.Exists(fullPath))
                        {
                            ModelState.AddModelError(string.Empty, "Image with the same name already exists.");
                            return View(image);
                        }

                        file.SaveAs(fullPath);
                        db.Images.Add(image);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(image);
        }

        // GET: Images/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image image = db.Images.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            ViewBag.Items = new SelectList(db.Items, "Id", "Name", image.ItemId);
            ViewBag.Stories = new SelectList(db.Stories, "Id", "Title", image.StoryId);
            ViewBag.Designers = new SelectList(db.Designers, "Id", "LastName", image.DesignerId);

            return View(image);
        }

        //POST: Images/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Url,Name,Description,ItemId,StoryId,DesignerId,IsThumb")] Image image)
        {

            if (ModelState.IsValid)
            {
                db.Entry(image).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            ViewBag.Items = new SelectList(db.Items, "Id", "Name", image.ItemId);
            ViewBag.Stories = new SelectList(db.Stories, "Id", "Title", image.StoryId);
            ViewBag.Designers = new SelectList(db.Designers, "Id", "LastName", image.DesignerId);


            return View(image);
        }


        // GET: Images/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image image = db.Images.Include(i => i.Item).Include(i => i.Story).Include(i => i.Item.Designer).FirstOrDefault(i => i.Id == id); ;
            if (image == null)
            {
                return HttpNotFound();
            }
            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Image image = db.Images.Find(id);
            System.IO.File.Delete(Server.MapPath(image.Url));
            db.Images.Remove(image);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Revolver/Revolver/Views/Images/Create.cshtml
@model Revolver.Models.Image

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Images", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
	<h4>Image</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.TextBoxFor(model => model.Url, new { type = "file" })
			@Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Name, "Image Name", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.ItemId, "Pullover Name", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("ItemId", null, "none", htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.StoryId, "Story Title", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("StoryId", null, "none", htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.StoryId, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.DesignerId, "Designer Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("DesignerId", null, "none", htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.DesignerId, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.IsThumb, "Thumbnail?", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.CheckBoxFor(model=> model.IsThumb)
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Create" class="btn btn-default" />
		</div>
	</div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Revolver/Revolver/Views/Images/Delete.cshtml
@model Revolver.Models.Image

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Image</h4>
    <hr />
	<dl class="dl-horizontal">

		<dt>
			<img src="@Url.Content(Model.Url)" style="width:100px" />
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Url)
		</dd>

		<dt>
			@Html.DisplayName("Image Name")
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

		<dt>
			@Html.DisplayName("Pullover Name")
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Item.Name)
		</dd>

		<dt>
			@Html.DisplayName("Story Title")
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Story.Title)
		</dd>

		<dt>
			@Html.DisplayName("Designer Name")
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Designer.Name)
			@Html.DisplayFor(model => model.Designer.LastName)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Description)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Description)
		</dd>

	</dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Revolver/Revolver/Views/Images/Details.cshtml
@model Revolver.Models.Image

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Image</h4>
    <hr />
	<dl class="dl-horizontal">
		<dt>
			<img src="@Url.Content(Model.Url)" style="width:100px" />
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Url)
		</dd>

		<dt>
			@Html.DisplayName("Image Name")
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

		<dt>
			@Html.DisplayName("Pullover Name")
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Item.Name)
		</dd>

		<dt>
			@Html.DisplayName("Story Title")
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Story.Title)
		</dd>

		<dt>
			@Html.DisplayName("Designer Name")
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Designer.Name)
			@Html.DisplayFor(model => model.Designer.LastName)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Description)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Description)
		</dd>

	</dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Revolver/Revolver/Views/Images/Edit.cshtml
@model Revolver.Models.Image

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Url)


        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				<img src="@Url.Content(Model.Url)" style="width:100px" />
			</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemId, "Item Name", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(m => m.ItemId, (SelectList)ViewBag.Items, "None Selected", new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
			</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoryId, "Story Title", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(m => m.StoryId, (SelectList)ViewBag.Stories, "None Selected", new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.StoryId, "", new { @class = "text-danger" })
			</div>
        </div>

		<div class="form-group">
            @Html.LabelFor(model => model.DesignerId, "Designer Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(m => m.DesignerId, (SelectList)ViewBag.Designers, "None Selected", new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.DesignerId, "", new { @class = "text-danger" })
			</div>
        </div>

		<div class="form-group">
			@Html.LabelFor(model => model.IsThumb, "Thumbnail?", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.CheckBoxFor(model=> model.IsThumb)
			</div>
		</div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Revolver/Revolver/Views/Images/Index.cshtml
@model IEnumerable<Revolver.Models.Image>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Url)
		</th>
		<th>
			@Html.DisplayName("Image Name")
		</th>
		<th>
			@Html.DisplayName("Pullover Name")
		</th>
		<th>
			@Html.DisplayName("Story Title")
		</th>
		<th></th>
	</tr>

@foreach (var item in Model) {
	<tr>
		<td>
			<img src="@Url.Content(item.Url)" style="width:100px" />
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Name)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Item.Name)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Story.Title)
		</td>
		<td>
			@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
			@Html.ActionLink("Details", "Details", new { id = item.Id }) |
			@Html.ActionLink("Delete", "Delete", new { id = item.Id })
		</td>
	</tr>
}

</table>