Revolver/Revolver/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Revolver.Models;

namespace Revolver.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Items
        public ActionResult Index()
        {
            var items = db.Items.Include(i => i.Designer).Include(i=>i.Images);
            
            ViewBag.CollectionId = new SelectList(Item.CollectionList, "value", "key");

            return View(items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Include(i => i.Designer).Include(i=>i.Images).FirstOrDefault(i => i.Id == id);
            ViewBag.CollectionId = new SelectList(Item.CollectionList, "value", "key", item.CollectionId);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            ViewBag.DesignerId = new SelectList(db.Designers, "Id", "LastName");
            ViewBag.CollectionId = new SelectList(Item.CollectionList, "value", "key");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DesignerId,Name,Price,Excerpt,Text,CollectionId,QuantityXS,QuantityS,QuantityM,QuantityL,QuantityXL")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DesignerId = new SelectList(db.Designers, "Id", "LastName", item.DesignerId);
            ViewBag.CollectionId = new SelectList(Item.CollectionList, "value", "key", item.CollectionId);
            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Include(i=>i.Designer).Include(i=>i.Images).FirstOrDefault(i=>i.Id==id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.DesignerId = new SelectList(db.Designers, "Id", "LastName", item.DesignerId);
            ViewBag.CollectionId = new SelectList(Item.CollectionList, "value", "key", item.CollectionId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DesignerId,Name,Price,Excerpt,Text,CollectionId,QuantityXS,QuantityS,QuantityM,QuantityL,QuantityXL")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DesignerId = new SelectList(db.Designers, "Id", "LastName", item.DesignerId);
            ViewBag.CollectionId = new SelectList(Item.CollectionList, "value", "key", item.CollectionId);
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Include(i => i.Designer).Include(i=>i.Images).FirstOrDefault(i => i.Id == id);
            ViewBag.CollectionId = new SelectList(Item.CollectionList, "value", "key", item.CollectionId);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Revolver/Revolver/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	@*<link rel="stylesheet" type="text/css" href="reset.css">
		<link rel="stylesheet" type="text/css" href="Site.css">*@
	<title>@ViewBag.Title - Revolver Pullover</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/jquery")

</head>
<body class="home_body">
    @RenderBody()
    <footer>
		<div class="bottom-section">
			<div class="subscription-section">
				<div class="subscription-title">Subscribe & get</div>
				<div class="subscription-amount">-10% OFF</div>
				<div class="subscription-email">
					<input id="emailNewsletter" placeholder="Your Email" />
				</div>
				<div class="subscription-button">
					<button id="subscribeButton">Subscribe</button>
				</div>
			</div>
			<div class="instagram-section">
				<div class="instagram-text">This is our collection with you. Share your story, share your style with us.</div>
				<div class="instagram-text2">#revolverpullover</div>
				<div class="social-buttons">
					<button class="button-igfollow">Follow</button><button class="button-fblike"><img class="fb-like-img" src="~/Resources/like.png" />Like</button>
				</div>
			</div>
			<!--    TODO fali onaj deo ceo oza instagram i fb like-->
			<div class="contact-section">
				@Html.Partial("ContactTable")
			</div>
			<div class="r-menu" id="openMenu"><sup class="CartQuantity">@Html.CartQuantity()</sup><span>R</span></div>
			<div id="menu" class="overlay">
				@Html.Partial("Menu")
				<div class="r-menu" id="closeMenu"><sup class="CartQuantity">@Html.CartQuantity()</sup><span>R</span></div>
			</div>
			<div id="subscription" class="overlay">
				<div class="close-button" id="closeSubscription">X</div>
				<div class="overlay-content" id="subscriptionPopup"></div>
			</div>
		</div>
    </footer>
    @*</div>*@
    @Scripts.Render("~/Scripts/Revolver.js")
    @RenderSection("scripts", required: false)
    @*<script type="text/javascript">
        function clickcont() {
        console.log("kliknuto je govno kontejner");
        }
    </script>*@
</body>
</html>

Revolver/Revolver/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Revolver", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li>@Html.ActionLink("Pullovers", "Index", "Items")</li>
						<li>@Html.ActionLink("Designers", "Index", "Designers")</li>
						<li>@Html.ActionLink("Images", "Index", "Images")</li>
						<li>@Html.ActionLink("Stories", "Index", "Stories")</li>
					</ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>